-- KACM Complete Seed Data
-- Run this in Supabase SQL Editor

-- ====== TESTIMONIALS ======
INSERT INTO testimonials (category, author, location, content, image, display_order, visible) VALUES
('sponsor', 'Sarah M.', 'United Kingdom', 'Sponsoring a child through KACM has been one of the most rewarding decisions of my life. I receive regular updates and see the direct impact of my support on my sponsored child''s education and wellbeing. The transparency and personal connection is unlike any other organisation I''ve supported.', 'assets/testimony-sponsor1.jpg', 1, true),
('sponsor', 'David K.', 'United States', 'I started sponsoring two children through KACM three years ago, and the transformation I''ve witnessed is incredible. From struggling to afford basic school supplies to now ranking among the top students — these children just needed someone to believe in them.', 'assets/testimony-sponsor2.jpg', 2, true),
('sponsor', 'Rebecca T.', 'Australia', 'What drew me to KACM was their holistic approach — they don''t just pay school fees; they invest in the child''s spiritual growth, nutrition, and emotional wellbeing. The letters I receive from my sponsored child are treasures. I visited Kazo last year and saw the love and dedication of the team.', 'assets/testimony-sponsor3.jpg', 3, true),
('child', 'Peter', 'Senior 3 · Kazo Parish', 'Before KACM, I could not afford school fees. My mother tried her best, but it was never enough. Now I am in Senior 3, and I dream of becoming a doctor. KACM gave me hope when I had none. I thank God for my sponsor every day.', 'assets/testimony-child1.jpg', 1, true),
('child', 'Agnes', 'Primary 6 · Kazo Parish', 'I love school. When my father passed away, I thought my education was over. But KACM found me a sponsor, and now I have books, a uniform, and food at school. I want to become a teacher so I can help other children like me.', 'assets/testimony-child2.jpg', 2, true),
('child', 'Brian', 'Senior 5 · Kazo Parish', 'The Resource Centre changed everything for me. I had never touched a computer before. Now I am learning ICT skills that will help me in university and beyond. KACM showed me that being from a village doesn''t limit my future.', 'assets/testimony-child3.jpg', 3, true),
('community', 'Mrs. Jane Kyomugisha', 'Parent · Kazo', 'As a widow with five children, I was overwhelmed. KACM not only sponsors two of my children''s education but also taught me farming techniques through Farm to Fork. Now I can feed my family and even sell surplus vegetables. KACM helped our whole family stand on our own feet.', 'assets/testimony-community1.jpg', 1, true),
('community', 'Mr. Charles Tumusiime', 'LC1 Chairman · Kazo', 'KACM has brought real change to our village. The community outreaches bring healthcare and food to families who would otherwise go without. Their child protection sensitisation has reduced cases of child abuse in our area. As a local leader, I fully endorse their work.', 'assets/testimony-community2.jpg', 2, true),
('community', 'Mrs. Doreen Ninsiima', 'Sunday School Teacher · Kazo', 'Teaching Sunday school used to be a challenge — we had no materials, no training. KACM equipped us with teaching guides, translated resources in Runyakitara, and training workshops. Now our children are more engaged than ever. They lead worship, they pray boldly, and they are growing in faith.', 'assets/testimony-community3.jpg', 3, true);

-- ====== PROJECTS ======
INSERT INTO projects (title, tagline, description, image, features, display_order, visible) VALUES
('Farm to Fork', 'From Our Land to Every Child''s Plate', 'The Farm to Fork project addresses the critical challenge of child malnutrition in the Kazo Archdeaconry. KACM cultivates organic food on ministry land, ensuring that children in our programmes have access to nutritious meals. Surplus produce is sold to generate income that is reinvested into meeting the basic needs of children.', 'assets/project-farming.jpg', 'Organic farming of vegetables, fruits, and grains||Agri-tourism activities supporting sustainable farming||Income generated reinvested into children''s welfare||Children learn practical agriculture and life skills', 1, true),
('Resource Centre', 'Equipping the Next Generation with Digital Skills', 'The KACM Resource Centre is an investment in the future. Recognising that digital skills are essential in today''s world, we have established a centre where young people gain ICT competencies, life skills, and vocational training that prepare them for employment, entrepreneurship, and responsible citizenship.', 'assets/project-computer-lab.jpg', 'Computer literacy training for students and out-of-school youth||Internet access and digital research support||Life skills workshops on leadership and financial literacy||Vocational guidance for career pathways', 2, true),
('Sponsor a Child', 'Your monthly sponsorship provides education, nutrition, and hope to a child in need.', 'The Sponsor a Child programme matches vulnerable children with generous sponsors worldwide. For as little as $20 a month, you can keep a child in school, clothed, and fed. Over 200 children are already sponsored through this life-changing programme.', 'assets/project-sponsor-child.jpg', 'Primary — Fees Only ($20/mo) covers school fees paid directly to school||Primary — Full Package ($30/mo) covers fees + books, uniform, supplies||Secondary — Fees Only ($35/mo) covers secondary school fees||Secondary — Full Package ($40/mo) covers fees + requirements||Secondary — Boarding ($70/mo) full boarding school package||Vocational / Tertiary ($75/mo) vocational or tertiary education fees||University Tuition ($116/mo) average university tuition', 3, true);

-- ====== HERO SLIDES ======
INSERT INTO hero_slides (heading, subtitle, scripture, button1_text, button1_link, button2_text, button2_link, background_image, display_order, visible) VALUES
('Kazo Archdeaconry Children''s Ministry', 'Nurturing Every Child in the Love of Christ — Kazo Archdeaconry, Uganda', '"Train up a child in the way he should go; even when he is old he will not depart from it." — Proverbs 22:6', 'Sponsor a Child', 'projects.html#sponsor', 'Learn More', 'about.html', 'assets/sunday school children group photos/sunday school children all combined.jpeg', 1, true),
('Give a Child the Gift of Education', 'For as little as $20 a month, you can keep a child in school, clothed, and fed.', '"The fear of the Lord is the beginning of wisdom, and knowledge of the Holy One is understanding." — Proverbs 9:10', 'Sponsor a Child', 'projects.html#sponsor', 'Donate Now', 'donate.html', 'assets/Sunday school children maganjo parish.jpeg', 2, true),
('Building Character Through Sport', 'Through football, netball, athletics, and the arts, we share the Gospel and build confidence in every child.', '"Whatever you do, work at it with all your heart, as working for the Lord, not for human masters." — Colossians 3:23', 'Explore Sports', 'index.html#programs', 'About Us', 'about.html', 'assets/Sunday school children kawanda parish.jpeg', 3, true),
('Bringing Hope to Vulnerable Families', 'Food distribution, healthcare, education support, and the Gospel — reaching every corner of the Archdeaconry.', '"For I was hungry and you gave me food, I was thirsty and you gave me drink, I was a stranger and you welcomed me." — Matthew 25:35', 'Our Outreach', 'index.html#programs', 'Read Stories', 'testimonies.html', 'assets/Sunday school lwadda parish.jpeg', 4, true);
